import React from "react";

import "../App.scss";

const Main = () => {
  return (
    <div className="main">
      <h1>Fate/Grand Order</h1>
      <h4>Rating: T</h4>
      <h4>Platforms: Android and iOS</h4>
      <h4>Initial Release Date: July 2015</h4>

      <p>
        Thank you for visiting this website. The API for the data was provided
        for free by the incredible team from{" "}
        <a href="https://api.atlasacademy.io/rapidoc">Atlas Academy</a>. It was
        generated by fans for fans.
      </p>
      <p>
        This website's purpose was to display the stats for each summonable
        character from the popular mobile gacha game Fate/Grand Order. Since the
        amount of data for each character was exeedingly large, I've only picked
        a few important stats to be rendered.
      </p>
      <p>
        The main focus for this application is to practice doing API calls and
        rendering data. One of the most difficult task for me was to generate a
        smooth layout that transitions from mobile, to tablet and desktop. Once
        the finishing touches for the character page is complete, I will move on
        to displaying the equipments available for the characters.
      </p>

      <p>
        Stay tuned! P.S.... if you think about joining the game, a fair warning
        - there will be lots of salt since its gacha ;D
      </p>

      <strong>
        Disclaimer: Due to the nature of the game having multiple guest
        designers, some of the character art may contain sensetive material.
        Viewer disgresion is advised.
      </strong>
    </div>
  );
};

export default Main;
